import React from 'react';
import styles from './body.module.css'

const Body = () => {
  return(
    <div className={styles.container}>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
      <div>body</div>
    </div>
    
  )
}

export default Body;